### ISSUE TITLE
cannot log data

### ISSUE THREAD

**Issue by wawachen** [JGSuw/rospy_crazyflie#2]
hi,

I install in python2.7 ros melodic.
when I RUN  the default.launch, no data is loging in topics.

**Comment by JGSuw** [comment]
Hello,

I'm sorry to hear about the difficulty. I don't recall having tested this on melodic, but I'm also not sure that the distribution would cause this issue. To date this repository has been tested with Kinetic Kame on the master branch (which was the original work), and most recently on Noetic in the python3-migration branch. 

I may be able to look into this issue tomorrow. Could you let me know a few things:

1) what tag of the crazyflie-firmware are you using and 
2) what tag of the crazyflie-lib-python have you installed in your environment

I think the crazyflie-lib-python version might have an impact in particular. Last I recall, on the master branch that was tested for Kinetic I was using a release tag from around January 2020.

Those would be helpful to see if I can reproduce this error using your environment.

**Comment by wawachen** [comment]
thank you for your response.

currently,  I use the latest firmware of crazyfile and the crazyfile-lib-python is the official one.
I have successfully run the take-off-land example, the drone can hover and land.

However, my question is that when I check the topics published from server.
use rostopic echo /some_topic, it gives me some error about **can not load this type message**. but I have use rosmsg to check this message is really existing in the environment, and I also make sure the devel/setup.bash has been sourced.

another question is that for this command like forward() and back(), how can I modify its controller's parameters (is it from the firmware)?

**Comment by JGSuw** [comment]
No worries.

Again, can you check for me specifically _which branch or release tag_ of the official crazyflie-lib-python you are using? Also, it would be super helpful if you could screen-shot the terminal when the error occurs. I want to see if I can reproduce it. It sounds like there is some problem in how the messages are being built or installed by catkin, but I can't say for sure until I have more information.

With regards to your other question, the position control based motion primitives are really just calling velocity commands (this is "open-loop" control). I assume that your crazyflie has the optical-flow deck installed, which provides groundspeed measurements to the drone. The velocity commands are sent over the radio and then executed by the crazyflie itself, which likely uses PID gains to turn velocity error into attitude and thrust. Such gains can most likely be changed using rospy-crazyflie, but you will need to dig into the firmware of the crazyflie to determine how the control works, and what parameters may be exposed for you to modify.

**Comment by wawachen** [comment]
libpython: master branch of https://github.com/bitcraze/crazyflie-lib-python
branch: python3-migration,

![Screenshot from 2021-07-08 12-02-22](https://user-images.githubusercontent.com/30148408/124911447-aa70f880-dfe4-11eb-953c-855e4d4f3417.png)

**Comment by JGSuw** [comment]
This is very useful, thank you. I just want a bit more information:

Is it just the MotorPower message that is not working, or are ControllerRPYT/KalmanPositionEst/Stabilizer also failing?

**Comment by wawachen** [comment]
yes, both are not working

**Comment by JGSuw** [comment]
Ok. I will try to see if I can recreate this problem using the installation documentation in the readme. Maybe that will reveal the problem, but again I suspect this is a build chain issue. If that is the case, then maybe the installation instructions are incorrect for that version of ROS.

**Comment by JGSuw** [comment]
Hi Oliver,

Just an update: I tested the master branch that uses python 2.7 on Ros Melodic today and I got it working, but I think the installation documentation needs a bit of cleanup, and I found a few other minor issues. The fixes are on a new branch called python27 now. On that branch I tested many of logging functions (Stabilizer, KalmanPositionEst, even custom log configs).  

I'll update the installation instructions in the Readme tomorrow morning.

**Comment by wawachen** [comment]
Hi,

Could you please test the melodic environment in python3?

I will very appreciate that.

Jingyu

Joseph Sullivan ***@***.***>于2021年7月13日 周二01:23写道：

**Comment by JGSuw** [comment]
To my knowledge Melodic only supports python 2, not python 3. Therefore,
you should instead use python 2 with Melodic. I personally do not have the
time right now to figure out how to build Melodic for python 3, my guess is
that it is not trivial.

I know for a fact that this repository works on Melodic.The only catch is
that it requires an older release of crazyflie-lib-python. I believe we
tested this yesterday using a release tag from January 2020. You can clone
all the old release tags from the official bitcraze repo.

I also know that the python3 branch of this repository works with ROS
Noetic. Since Noetic supports python 3, if you need python 3, then you
should install Noetic and not Melodic.

**Comment by wawachen** [comment]
well, Thanks for your support!
